export { getAppSpec } from './getAppSpec'
export { getDetail } from './getDetail'
export type { GetDetail } from './getDetail'
export { getTableData } from './getTableData'
export type { GetTableData } from './getTableData'
export { getTableSpec } from './getTableSpec'
