export const listMenu = [
  { label: 'Avatar', href: '/docs/avatar' },
  { label: 'Badge', href: '/docs/badge' },
  { label: 'Button', href: '/docs/button' },
  { label: 'Checkbox', href: '/docs/checkbox' },
  { label: 'Dropdown', href: '/docs/dropdown' },
  { label: 'FormLowcode', href: '/docs/formlowcode' },
  { label: 'FormLowcodeLite', href: '/docs/formlowcodelite' },
  { label: 'Input', href: '/docs/input' },
  { label: 'InputDate', href: '/docs/inputdate' },
  { label: 'InputWithModal', href: '/docs/inputwithmodal' },
  { label: 'InputYear', href: '/docs/inputyear' },
  { label: 'Modal', href: '/docs/modal' },
  { label: 'ModalWithState', href: '/docs/modalwithstate' },
  { label: 'PendingUpload', href: '/docs/pendingupload' },
  { label: 'Radio', href: '/docs/radio' },
  { label: 'ReactHookWrapper', href: '/docs/reacthookwrapper' },
  { label: 'Sidebar', href: '/docs/sidebar' },
  { label: 'Select', href: '/docs/select' },
  { label: 'Skeleton', href: '/docs/skeleton' },
  { label: 'Spinner', href: '/docs/spinner' },
  { label: 'Switch', href: '/docs/switch' },
  { label: 'TableLowcode', href: '/docs/tablelowcode' },
  { label: 'Tag', href: '/docs/tag' },
  { label: 'Tooltip', href: '/docs/tooltip' },
]
