import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Alurkerja',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header>header</header>
      <div className="lg:flex">
        <div className="fixed inset-0 z-50 h-full w-64 flex-none border-r border-gray-200 lg:static lg:block lg:h-auto lg:overflow-y-visible lg:pt-6">
          Sidebar
        </div>
        <div className="w-full min-w-0 flex-auto lg:static lg:max-h-full lg:overflow-visible">
          <div className="flex w-full">
            <div className="pb:12 mx-auto flex min-w-0 max-w-4xl flex-col divide-y divide-gray-200 px-4 pt-6 dark:divide-gray-800 lg:px-8 lg:pb-16 lg:pt-8 xl:pb-24">
              <main>{children}</main>
              <footer>
                <hr className="w-full my-6 border-gray-200 sm:mx-auto  lg:my-8" />
                <div className="text-gray-500 sm:text-center text-base">
                  © 2023
                  <a href="/" className="ml-1 hover:underline">
                    Alurkerja
                  </a>
                </div>
              </footer>
            </div>
            <aside className="right-0 hidden w-64 flex-none pl-8 xl:block xl:text-sm">
              Aside
            </aside>
          </div>
        </div>
      </div>
    </>
  )
}
